// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	Title   string `json:"title"`
	Body    string `json:"body"`
	Created string `json:"created"`
}

func (Post) IsEntity() {}

type User struct {
	ID    string  `json:"id"`
	Posts []*Post `json:"posts"`
}

func (User) IsEntity() {}
