services:
  rest:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: rest
    entrypoint: ./services/rest/rest/server

    environment:
      - PORT=3100

    ports:
      - "3100:3100"

  users-rest:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: users-rest
    entrypoint: ./services/rest/users/server

    environment:
      - PORT=3101

    ports:
      - "3101:3101"

  posts-rest:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: posts-rest
    entrypoint: ./services/rest/posts/server

    environment:
      - PORT=3102

    ports:
      - "3102:3102"

  comments-rest:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: comments-rest
    entrypoint: ./services/rest/comments/server

    environment:
      - PORT=3103

    ports:
      - "3103:3103"

  users-graph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: users-graph
    entrypoint: ./services/graphql/users/server

    environment:
      - PORT=4101

    ports:
      - "4101:4101"

  posts-graph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: posts-graph
    entrypoint: ./services/graphql/posts/server

    environment:
      - PORT=4102

    ports:
      - "4102:4102"

  comments-graph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: comments-graph
    entrypoint: ./services/graphql/comments/server

    environment:
      - PORT=4103

    ports:
      - "4103:4103"

  notifications-graph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: notifications-graph
    entrypoint: ./services/graphql/notifications/server

    environment:
      - PORT=4104

    ports:
      - "4104:4104"

  users-subgraph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: users-subgraph
    entrypoint: ./services/graphql-subgraphs/users/server

    environment:
      - PORT=4201

    ports:
      - "4201:4201"

  posts-subgraph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: posts-subgraph
    entrypoint: ./services/graphql-subgraphs/posts/server

    environment:
      - PORT=4202

    ports:
      - "4202:4202"

  comments-subgraph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: comments-subgraph
    entrypoint: ./services/graphql-subgraphs/comments/server

    environment:
      - PORT=4203

    ports:
      - "4203:4203"

  notifications-subgraph:
    image: zalbiraw/go-api-test-service:v3.3.0
    container_name: notifications-subgraph
    entrypoint: ./services/graphql-subgraphs/notifications/server

    environment:
      - PORT=4204

    ports:
      - "4204:4204"