// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Notification struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

func (Notification) IsEntity() {}

type User struct {
	ID            string          `json:"id"`
	Notifications []*Notification `json:"notifications-subgraph"`
}

func (User) IsEntity() {}
